name: Update images.json

on:
  push:
    paths:
      - 'images/**'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate images.json
        run: |
          echo "[" > images.json
          for f in images/*; do
            if [ -f "$f" ]; then
              echo "  \"$(basename "$f")\"," >> images.json
            fi
          done
          sed -i '$ s/,$//' images.json
          echo "]" >> images.json

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add images.json
          git commit -m "Update images.json" || echo "No changes to commit"
          git push
